#!/bin/sh
# Simple Cloud Firewall using IPTables

IPT="/usr/sbin/iptables"

case "$1" in
  start)
    echo "Starting Firewall..."
    
    # 1. Flush existing rules
    $IPT -F
    $IPT -X
    
    # 2. Set Default Policies (DROP Input, ACCEPT Output)
    $IPT -P INPUT DROP
    $IPT -P FORWARD DROP
    $IPT -P OUTPUT ACCEPT
    
    # 3. Allow Loopback (Localhost)
    $IPT -A INPUT -i lo -j ACCEPT
    
    # 4. Allow Established Connections (Replies to our requests)
    $IPT -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    
    # 5. Allow SSH (Port 22)
    $IPT -A INPUT -p tcp --dport 22 -j ACCEPT
    
    # 6. Allow Simple-Server (Port 8080)
    $IPT -A INPUT -p tcp --dport 8080 -j ACCEPT
    
    # 7. Allow ICMP (Ping)
    $IPT -A INPUT -p icmp -j ACCEPT
    
    # 8. Log Dropped Packets (Optional, good for debugging)
    # $IPT -A INPUT -j LOG --log-prefix "FIREWALL:DROP: "
    ;;
  stop)
    echo "Stopping Firewall (Allowing all traffic)..."
    $IPT -P INPUT ACCEPT
    $IPT -P FORWARD ACCEPT
    $IPT -P OUTPUT ACCEPT
    $IPT -F
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
