#!/bin/sh
# Start/Stop Simple-Server

DAEMON="/usr/bin/server"
PIDFILE="/var/run/server.pid"

case "$1" in
  start)
    echo "Starting Simple-Server..."
    start-stop-daemon -S -b -m -p $PIDFILE -x $DAEMON
    ;;
  stop)
    echo "Stopping Simple-Server..."
    start-stop-daemon -K -p $PIDFILE
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
